namespace smc.generator.csharp.CSharpCodeGenerators
{
    using System.Text;

    using smc.fsmrep;
    using smc.generator.csharp;

    public class InitialComments : CSharpCodeGenerator
    {
        #region Public Methods

        public override string generateCode(SMCSharpGenerator smcsg)
        {
            var stateMap = smcsg.getStateMap();

            var buff = new StringBuilder()
                .AppendLine("// <auto-generated />")
                .AppendLine("//-----------------------------------------------------------------------")
                .AppendLine($"// FSM:       {stateMap.getName()}")
                .AppendLine($"// Context:   {stateMap.getContextName()}")
                .AppendLine(GetErrorStrategy(stateMap, smcsg.usesExceptions(stateMap)))
                .AppendLine($"// Version:   {stateMap.getVersion()}")
                .AppendLine("//-----------------------------------------------------------------------")
                .AppendLine();

            return buff.ToString();
        }

        #endregion

        #region Methods

        private string GetErrorStrategy(StateMap stateMap, bool usesExceptions)
        {
            return usesExceptions
                ? $"// Exception: {stateMap.getExceptionName()}"
                : $"// Err Func:  {stateMap.getErrorFunctionName()}";
        }

        #endregion
    }
}