namespace SMC.Generator.CSharp.CSharpCodeGenerators
{
    using System.Text;

    using SMC.FsmRep;
    using SMC.Generator.CSharp;

    public class InitialComments : CSharpCodeGenerator
    {
        #region Public Methods

        public override string GenerateCode(SMCSharpGenerator smcsg)
        {
            var stateMap = smcsg.StateMap;

            var buff = new StringBuilder()
                .AppendLine("// <auto-generated />")
                .AppendLine("//-----------------------------------------------------------------------")
                .AppendLine($"// FSM:       {stateMap.Name}")
                .AppendLine($"// Context:   {stateMap.ContextName}")
                .AppendLine(GetErrorStrategy(stateMap, stateMap.UsesExceptions))
                .AppendLine($"// Version:   {stateMap.Version}")
                .AppendLine("//-----------------------------------------------------------------------")
                .AppendLine();

            return buff.ToString();
        }

        #endregion

        #region Methods

        private string GetErrorStrategy(StateMap stateMap, bool usesExceptions)
        {
            return usesExceptions
                ? $"// Exception: {stateMap.ExceptionName}"
                : $"// Err Func:  {stateMap.ErrorFunctionName}";
        }

        #endregion
    }
}